import { AIChatAgent, type OnChatMessageOptions } from "@cloudflare/ai-chat";
import { streamText, convertToModelMessages, tool, stepCountIs, type ToolSet, type StreamTextOnFinishCallback } from "ai";
import { createWorkersAI } from "workers-ai-provider";
import { routeAgentRequest } from "agents";
import { z } from "zod";

// ---------------------------------------------------------------------------
// Env type is generated by `wrangler types` → worker-configuration.d.ts
// Add CF_API_TOKEN (secret) manually since wrangler types doesn't include secrets
// ---------------------------------------------------------------------------

type FullEnv = Env & { CF_API_TOKEN: string };

// ---------------------------------------------------------------------------
// Cloudflare API helpers
// ---------------------------------------------------------------------------

async function cfApi(
  env: FullEnv,
  path: string,
  options?: RequestInit
): Promise<unknown> {
  const res = await fetch(`https://api.cloudflare.com/client/v4${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${env.CF_API_TOKEN}`,
      "Content-Type": "application/json",
      ...(options?.headers ?? {}),
    },
  });
  const json = (await res.json()) as { success: boolean; errors?: unknown[]; result?: unknown; messages?: unknown[] };
  if (!json.success) {
    throw new Error(`Cloudflare API error: ${JSON.stringify(json.errors)}`);
  }
  return json.result;
}

// ---------------------------------------------------------------------------
// Zero Trust tool definitions
// ---------------------------------------------------------------------------

function makeTools(env: FullEnv) {
  const acct = `/accounts/${env.CF_ACCOUNT_ID}`;

  return {
    // -------- Access --------------------------------------------------------

    listAccessApps: tool({
      description:
        "List all Cloudflare Access applications configured in the account.",
      inputSchema: z.object({}),
      execute: async () => {
        return await cfApi(env, `${acct}/access/apps`);
      },
    }),

    getAccessApp: tool({
      description: "Get details of a specific Access application by its UUID.",
      inputSchema: z.object({
        appId: z.string().describe("UUID of the Access application"),
      }),
      execute: async ({ appId }) => {
        return await cfApi(env, `${acct}/access/apps/${appId}`);
      },
    }),

    createAccessApp: tool({
      description:
        "Create a new Cloudflare Access application. Supports self-hosted apps (public hostname), SaaS apps (SAML/OIDC), and non-HTTP apps.",
      inputSchema: z.object({
        name: z.string().describe("Friendly display name"),
        domain: z
          .string()
          .optional()
          .describe("Public hostname for self-hosted apps (e.g. app.example.com)"),
        type: z
          .enum(["self_hosted", "saas", "ssh", "vnc", "app_launcher", "warp", "biso", "bookmark"])
          .default("self_hosted")
          .describe("Application type"),
        sessionDuration: z
          .string()
          .default("24h")
          .describe("Session duration, e.g. 24h, 7d"),
      }),
      execute: async ({ name, domain, type, sessionDuration }) => {
        const body: Record<string, unknown> = { name, type, session_duration: sessionDuration };
        if (domain) body.domain = domain;
        return await cfApi(env, `${acct}/access/apps`, {
          method: "POST",
          body: JSON.stringify(body),
        });
      },
    }),

    listAccessPolicies: tool({
      description: "List all policies attached to a specific Access application.",
      inputSchema: z.object({
        appId: z.string().describe("UUID of the Access application"),
      }),
      execute: async ({ appId }) => {
        return await cfApi(env, `${acct}/access/apps/${appId}/policies`);
      },
    }),

    createAccessPolicy: tool({
      description:
        "Create an Access policy for an application. Policies are default-deny; you must create an Allow policy to grant access.",
      inputSchema: z.object({
        appId: z.string().describe("UUID of the Access application"),
        name: z.string().describe("Policy name"),
        decision: z
          .enum(["allow", "deny", "non_identity", "bypass"])
          .describe("Policy action"),
        precedence: z.number().int().default(1).describe("Evaluation order (lower = higher priority)"),
        includeEmails: z
          .array(z.string())
          .optional()
          .describe("List of allowed email addresses"),
        includeEmailDomains: z
          .array(z.string())
          .optional()
          .describe("List of allowed email domains (e.g. example.com)"),
        includeGroups: z
          .array(z.string())
          .optional()
          .describe("List of Access Group IDs to include"),
      }),
      execute: async ({ appId, name, decision, precedence, includeEmails, includeEmailDomains, includeGroups }) => {
        const include: unknown[] = [];
        if (includeEmails?.length) include.push(...includeEmails.map((e) => ({ email: { email: e } })));
        if (includeEmailDomains?.length) include.push(...includeEmailDomains.map((d) => ({ email_domain: { domain: d } })));
        if (includeGroups?.length) include.push(...includeGroups.map((id) => ({ group: { id } })));

        return await cfApi(env, `${acct}/access/apps/${appId}/policies`, {
          method: "POST",
          body: JSON.stringify({ name, decision, precedence, include }),
        });
      },
    }),

    listAccessGroups: tool({
      description: "List all reusable Access Groups in the account.",
      inputSchema: z.object({}),
      execute: async () => {
        return await cfApi(env, `${acct}/access/groups`);
      },
    }),

    // -------- Gateway -------------------------------------------------------

    listGatewayRules: tool({
      description:
        "List Gateway filtering rules. Optionally filter by traffic type: dns, http, or network (L4). Returns rules with name, action, traffic expression, and enabled status.",
      inputSchema: z.object({
        trafficType: z
          .enum(["dns", "http", "network", "egress"])
          .optional()
          .describe("Filter by rule traffic type"),
      }),
      execute: async ({ trafficType }) => {
        const url = trafficType
          ? `${acct}/gateway/rules?traffic_type=${trafficType}`
          : `${acct}/gateway/rules`;
        return await cfApi(env, url);
      },
    }),

    createGatewayRule: tool({
      description:
        "Create a new Gateway filtering rule (DNS, HTTP, or Network). Start rules as disabled unless the user explicitly confirms enabling them immediately.",
      inputSchema: z.object({
        name: z.string().describe("Rule name"),
        description: z.string().optional().describe("Optional description"),
        trafficType: z
          .enum(["dns", "http", "network", "egress"])
          .describe("Traffic type this rule applies to"),
        expression: z
          .string()
          .describe(
            "Wirefilter expression, e.g. 'dns.qtype == \"A\" and dns.fqdn in $malware_list' or 'http.request.uri.path contains \"/admin\"'"
          ),
        action: z
          .enum(["allow", "block", "safesearch", "ytrestricted", "isolate", "noisolate", "override", "l4_override", "egress", "audit_ssh", "resolve"])
          .describe("Rule action"),
        enabled: z.boolean().default(false).describe("Whether to enable immediately"),
        precedence: z.number().int().optional().describe("Rule precedence (lower = evaluated first)"),
      }),
      execute: async ({ name, description, trafficType, expression, action, enabled, precedence }) => {
        const body: Record<string, unknown> = {
          name,
          description,
          traffic: trafficType,
          filters: [trafficType],
          action: { type: action },
          conditions: [{ type: "traffic", expression }],
          enabled,
        };
        if (precedence !== undefined) body.precedence = precedence;
        return await cfApi(env, `${acct}/gateway/rules`, {
          method: "POST",
          body: JSON.stringify(body),
        });
      },
    }),

    toggleGatewayRule: tool({
      description: "Enable or disable an existing Gateway rule.",
      inputSchema: z.object({
        ruleId: z.string().describe("UUID of the Gateway rule"),
        enabled: z.boolean().describe("true to enable, false to disable"),
      }),
      execute: async ({ ruleId, enabled }) => {
        return await cfApi(env, `${acct}/gateway/rules/${ruleId}`, {
          method: "PATCH",
          body: JSON.stringify({ enabled }),
        });
      },
    }),

    listGatewayLists: tool({
      description: "List custom Gateway lists (IP lists, domain lists, URL lists).",
      inputSchema: z.object({}),
      execute: async () => {
        return await cfApi(env, `${acct}/gateway/lists`);
      },
    }),

    getGatewaySettings: tool({
      description: "Get account-level Gateway settings (TLS inspection status, proxy ports, anti-virus, DNS over HTTPS, etc.).",
      inputSchema: z.object({}),
      execute: async () => {
        return await cfApi(env, `${acct}/gateway`);
      },
    }),

    // -------- Tunnels -------------------------------------------------------

    listTunnels: tool({
      description: "List all Cloudflare Tunnels in the account with their status (healthy, down, inactive).",
      inputSchema: z.object({
        status: z
          .enum(["active", "inactive", "degraded", "down"])
          .optional()
          .describe("Filter by tunnel status"),
      }),
      execute: async ({ status }) => {
        const url = status
          ? `${acct}/cfd_tunnel?status=${status}`
          : `${acct}/cfd_tunnel`;
        return await cfApi(env, url);
      },
    }),

    getTunnel: tool({
      description: "Get detailed information and connector status for a specific Cloudflare Tunnel.",
      inputSchema: z.object({
        tunnelId: z.string().describe("UUID of the tunnel"),
      }),
      execute: async ({ tunnelId }) => {
        const [tunnel, connections] = await Promise.all([
          cfApi(env, `${acct}/cfd_tunnel/${tunnelId}`),
          cfApi(env, `${acct}/cfd_tunnel/${tunnelId}/connections`).catch(() => null),
        ]);
        return { tunnel, connections };
      },
    }),

    getTunnelConfig: tool({
      description: "Get the ingress configuration for a Cloudflare Tunnel (hostnames, services, and origin rules).",
      inputSchema: z.object({
        tunnelId: z.string().describe("UUID of the tunnel"),
      }),
      execute: async ({ tunnelId }) => {
        return await cfApi(env, `${acct}/cfd_tunnel/${tunnelId}/configurations`);
      },
    }),

    createTunnel: tool({
      description:
        "Create a new Cloudflare Tunnel. Returns the tunnel ID and a token used to run cloudflared connectors.",
      inputSchema: z.object({
        name: z.string().describe("Tunnel name (must be unique in the account)"),
        configSrc: z
          .enum(["cloudflare", "local"])
          .default("cloudflare")
          .describe("cloudflare = remotely managed via dashboard/API; local = config file on connector host"),
      }),
      execute: async ({ name, configSrc }) => {
        return await cfApi(env, `${acct}/cfd_tunnel`, {
          method: "POST",
          body: JSON.stringify({ name, config_src: configSrc }),
        });
      },
    }),

    // -------- WARP / Device -------------------------------------------------

    listDeviceProfiles: tool({
      description: "List WARP device profiles (also called device settings policies). Shows split tunnel mode, TLS inspection, and other per-profile settings.",
      inputSchema: z.object({}),
      execute: async () => {
        const [defaultPolicy, policies] = await Promise.all([
          cfApi(env, `${acct}/devices/policy`),
          cfApi(env, `${acct}/devices/policies`),
        ]);
        return { defaultProfile: defaultPolicy, additionalProfiles: policies };
      },
    }),

    getSplitTunnelConfig: tool({
      description: "Get the split tunnel include or exclude list for a specific WARP device profile.",
      inputSchema: z.object({
        policyId: z
          .string()
          .optional()
          .describe("Profile UUID. Omit to use the default profile."),
        mode: z
          .enum(["include", "exclude"])
          .describe("Whether to fetch include routes or exclude routes"),
      }),
      execute: async ({ policyId, mode }) => {
        const base = policyId
          ? `${acct}/devices/policy/${policyId}`
          : `${acct}/devices/policy`;
        return await cfApi(env, `${base}/${mode}`);
      },
    }),

    listEnrolledDevices: tool({
      description: "List devices enrolled in WARP, with their status, platform, and last-seen timestamp.",
      inputSchema: z.object({
        search: z.string().optional().describe("Filter by hostname or user email"),
      }),
      execute: async ({ search }) => {
        const url = search
          ? `${acct}/devices?search=${encodeURIComponent(search)}`
          : `${acct}/devices`;
        return await cfApi(env, url);
      },
    }),

    // -------- Logs & Analytics ----------------------------------------------

    queryGatewayLogs: tool({
      description:
        "Query recent Gateway activity logs using the Cloudflare GraphQL analytics API. Returns recent DNS, HTTP, or Network events filtered by user, action, domain, or IP.",
      inputSchema: z.object({
        trafficType: z
          .enum(["dns", "http", "network"])
          .describe("Log type to query"),
        limit: z.number().int().min(1).max(100).default(25).describe("Number of records to return"),
        since: z
          .string()
          .optional()
          .describe("ISO 8601 start time, e.g. 2025-06-01T00:00:00Z. Defaults to the last 1 hour."),
        filterAction: z
          .enum(["block", "allow", "override"])
          .optional()
          .describe("Filter by Gateway action"),
        filterEmail: z.string().optional().describe("Filter by user email"),
      }),
      execute: async ({ trafficType, limit, since, filterAction, filterEmail }) => {
        const now = new Date();
        const start = since ?? new Date(now.getTime() - 60 * 60 * 1000).toISOString();
        const end = now.toISOString();

        // Map to GraphQL dataset names
        const datasetMap: Record<string, string> = {
          dns: "gatewayResolverResultsAdaptiveGroups",
          http: "gatewayHttpsResultsAdaptiveGroups",
          network: "gatewayNetworkResultsAdaptiveGroups",
        };
        const dataset = datasetMap[trafficType];

        // Basic filter conditions
        const filterParts: string[] = [
          `datetime_geq: "${start}"`,
          `datetime_leq: "${end}"`,
        ];
        if (filterAction) filterParts.push(`action: "${filterAction}"`);
        if (filterEmail) filterParts.push(`userEmail: "${filterEmail}"`);

        const query = `{
          viewer {
            accounts(filter: {accountTag: "${env.CF_ACCOUNT_ID}"}) {
              ${dataset}(
                limit: ${limit},
                filter: { ${filterParts.join(", ")} },
                orderBy: [datetime_DESC]
              ) {
                dimensions {
                  action
                  datetime
                  ${trafficType === "dns" ? "queryName\nuserEmail" : "destinationIP\nrequestURL\nuserEmail"}
                }
              }
            }
          }
        }`;

        const res = await fetch("https://api.cloudflare.com/client/v4/graphql", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${env.CF_API_TOKEN}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ query }),
        });
        return await res.json();
      },
    }),

    getAccessAuditLogs: tool({
      description: "Query Access authentication audit logs to see who accessed which applications and when.",
      inputSchema: z.object({
        appId: z.string().optional().describe("Filter by Access application UUID"),
        userEmail: z.string().optional().describe("Filter by user email"),
        since: z.string().optional().describe("ISO 8601 start time. Defaults to last 24 hours."),
        limit: z.number().int().min(1).max(100).default(25).describe("Number of records to return"),
      }),
      execute: async ({ appId, userEmail, since, limit }) => {
        const params = new URLSearchParams({ per_page: String(limit) });
        if (appId) params.set("app_uid", appId);
        if (userEmail) params.set("email", userEmail);
        if (since) params.set("since", since);
        return await cfApi(env, `${acct}/access/logs/access_requests?${params}`);
      },
    }),
  };
}

// ---------------------------------------------------------------------------
// Agent
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are a Cloudflare Zero Trust management agent — an expert assistant that helps administrators configure and operate their Zero Trust environment through natural language.

You have access to tools that interact directly with the Cloudflare API to manage:
- **Access**: applications, policies, and groups (identity-aware application authorization)
- **Gateway**: DNS, HTTP, and Network filtering rules and custom lists (traffic inspection)
- **Tunnels**: Cloudflare Tunnel creation and ingress configuration (private network connectivity)
- **WARP / Devices**: device profiles, split tunnel settings, and enrolled device inventory
- **Logs**: Gateway activity logs and Access authentication audit logs

Guidelines:
1. Always show the user what API call you're about to make and confirm before any CREATE, UPDATE, or DELETE operation that could affect production traffic.
2. Create Gateway rules and Access policies as **disabled** by default unless the user explicitly asks to enable immediately.
3. When asked to troubleshoot, query logs first, then inspect the relevant rules/policies.
4. Be explicit about security implications — e.g. warn if a policy would allow unauthenticated access.
5. Cite the Cloudflare Zero Trust docs URL when explaining concepts the user may want to read more about.
6. If you are unsure of the correct wirefilter expression syntax or API field, say so rather than guessing.`;

export class ZeroTrustAgent extends AIChatAgent<FullEnv> {
  async onChatMessage(
    onFinish: StreamTextOnFinishCallback<ToolSet>,
    options?: OnChatMessageOptions
  ) {
    try {
      const workersai = createWorkersAI({ binding: this.env.AI });
      const modelMessages = await convertToModelMessages(this.messages);

      console.log("[ZTA] onChatMessage — messages:", modelMessages.length, "tools:", Object.keys(makeTools(this.env)).length);

      const result = streamText({
        model: workersai("@cf/meta/llama-3.3-70b-instruct"),
        system: SYSTEM_PROMPT,
        messages: modelMessages,
        tools: makeTools(this.env),
        stopWhen: stepCountIs(10),
        abortSignal: options?.abortSignal,
        onError: (e) => console.error("[ZTA] streamText onError:", e),
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        onFinish: onFinish as any,
      });

      return result.toUIMessageStreamResponse();
    } catch (err) {
      console.error("[ZTA] onChatMessage threw:", err);
      throw err;
    }
  }
}

// ---------------------------------------------------------------------------
// Worker entry point
// ---------------------------------------------------------------------------

export default {
  async fetch(request: Request, env: FullEnv): Promise<Response> {
    // Route agent WebSocket + HTTP requests
    const agentResponse = await routeAgentRequest(request, env);
    if (agentResponse) return agentResponse;

    // Fall back to static assets (the chat UI)
    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<FullEnv>;
